# Generated by Django 6.0.3 on 2026-06-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_tutor_historicopeso_pet_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='veterinario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
